-- MySQL Script generated by MySQL Workbench
-- Wed Sep 23 07:41:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema financeiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema financeiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `financeiro` DEFAULT CHARACTER SET utf8 ;
USE `financeiro` ;

-- -----------------------------------------------------
-- Table `financeiro`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `Data_Nascimento` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`Conta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Saldo` DECIMAL(9,2) NOT NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Usuario_Id`),
  INDEX `fk_Conta_Usuario_idx` (`Usuario_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Usuario`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `financeiro`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`Plano_Contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`Plano_Contas` (
  `idPlano_Contas` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `Tipo` CHAR(1) NULL,
  PRIMARY KEY (`idPlano_Contas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`Transacao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Data` DATETIME NOT NULL,
  `Tipo` CHAR(1) NOT NULL,
  `Valor` DECIMAL(9,2) NOT NULL,
  `Descricacao` VARCHAR(45) NOT NULL,
  `Conta_Id` INT NOT NULL,
  `Conta_Usuario_Id` INT NOT NULL,
  `Plano_Contas_idPlano_Contas` INT NOT NULL,
  PRIMARY KEY (`Id`, `Conta_Id`, `Conta_Usuario_Id`, `Plano_Contas_idPlano_Contas`),
  INDEX `fk_Transacao_Conta1_idx` (`Conta_Id` ASC, `Conta_Usuario_Id` ASC) VISIBLE,
  INDEX `fk_Transacao_Plano_Contas1_idx` (`Plano_Contas_idPlano_Contas` ASC) VISIBLE,
  CONSTRAINT `fk_Transacao_Conta1`
    FOREIGN KEY (`Conta_Id` , `Conta_Usuario_Id`)
    REFERENCES `financeiro`.`Conta` (`Id` , `Usuario_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Plano_Contas1`
    FOREIGN KEY (`Plano_Contas_idPlano_Contas`)
    REFERENCES `financeiro`.`Plano_Contas` (`idPlano_Contas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
